from cgi import print_arguments


print("------------------------")
print("THIS IS A MADLIB GAME")
print("------------------------")
print("According to Wikipedia, Mad Libs is a phrasal template word game,")
print("usually played at parties,where one player prompts other players for a") 
print("list of words to substitute blanks in a story before reading out the completed story aloud")
print()
print('Please enter the following: ')
adjective = input('Adjective: ')
animal = input('Animal: ')
verb = input('Verb: ')
exclamation = input('Exclamation: ')
verb1 = input('Verb: ')
verb2 = input('Verb: ')
exclamation1 = input('Exclamation: ')
a_day = input('A day: ')
adjective1 = input('Adjective: ')
adjective2 = input('Adjective: ')
adjective3 = input('Adjective: ')
print()
print('Your story is: ')
print()
print(f'The other day, I was really in trouble. It all started when I saw a very')
print(f'{adjective.lower()} {animal.lower()} {verb.lower()} down the hallway. "{exclamation.capitalize()}!" I yelled. But all')
print(f'I could think to do was to {verb1.lower()} over and over. Miraculously,')
print(f'that caused it to stop, but not before it tried to {verb2.lower()}')
print(f'right in front of my family.')
print(f'{exclamation1.capitalize()}! That {a_day.capitalize()}, it was a really {adjective1.lower()} and {adjective2.lower()} day!')
print(f'Do you have any {adjective3.lower()} story to tell?')
