import turtle
ks_bloom= turtle.Turtle()
print("THIS PROGRAM WILL DRAW A GEOMETRIC SHAPE THAT YOU WANT\n")
print("PLEASE CHOSE ONE \n SQUARE \n RECTANGLE \n TRIANGLE \n CIRCLE \n LOSANGE")
any_shape=input("what geometric shape would you like to draw?")
ks_bloom.shape("turtle")
bg_color=input("what background color do you like:red,bleu,white...")
#ks_bloom.bgcolor(bg_color)
#ks bloom.bgpic(r"c:\\\\\")
#ks bloom.bgpic()
#ks_bloom.scrensize(1500,1000)
#ks_bloom.title("vacadige")
pen_size=int(input("please enter the pen size"))
ks_bloom.pensize(pen_size)
pen_color=input("Enter the pen color")
ks_bloom.pencolor(pen_color)
fill_color=input("Enter the fill color")
ks_bloom.fillcolor(fill_color)
if any_shape.lower()=="square":
    length=int(input("Enter the length:"))
    ks_bloom.begin_fill()
    ks_bloom.forward(length)
    ks_bloom.left(90)
    ks_bloom.forward(length)
    ks_bloom.left(90)
    ks_bloom.forward(length)
    ks_bloom.left(90)
    ks_bloom.forward(length)
    ks_bloom.end_fill()
elif any_shape.lower()=="rectangle":
    length=int(input("Enter the length"))
    width=int(input("Enter the wifth"))
    ks_bloom.begin_fill()
    ks_bloom.forward(length)
    ks_bloom.right(90)
    ks_bloom.forward(width)
    ks_bloom.right(90)
    ks_bloom.forward(length)
    ks_bloom.right(90)
    ks_bloom.forward(width)
    ks_bloom.end_fill()
elif any_shape=="circle":
    ks_bloom.begin_fill()
    radiant=int(input("Enter the radiant"))
    ks_bloom.circle(radiant)
    ks_bloom.end_fill()
elif any_shape=="triangle":
    ks_bloom.begin_fill()
    side=int(input("Enter the side length"))
    ks_bloom.forward(side)
    ks_bloom.left(135)
    ks_bloom.forward(side)
    ks_bloom.left(90)
    ks_bloom.forward(side)
    ks_bloom.left(135)
    ks_bloom.forward(side)
    ks_bloom.end_fill()
elif any_shape=="losange":
    ks_bloom.begin_fill()
    side=int(input("Enter the side length"))
    ks_bloom.left(135)
    ks_bloom.forward(side)
    ks_bloom.left(90)
    ks_bloom.forward(side)
    ks_bloom.left(90)
    ks_bloom.forward(side)
    ks_bloom.left(90)
    ks_bloom.forward(side)
    ks_bloom.end_fill()
    
    
    
