print("THIS PROGRAM DISPLAY A TABLE THAT YOU LIKE:MULT,DIVISION,ADD,SUBSTR")
print("what table would you like:")
print("multiplication")
print("division")
print("addition")
print("substraction")
table=input("Enter the table you like:")
num=int(input("please enter a number"))
if table.lower()=="multiplication":
    print(num,"x 1 =",num*1)
    print(num,"x 2 =",num*2)
    print(num,"x 3 =",num*3)
    print(num,"x 4 =",num*4)
    print(num,"x 5 =",num*5)
    print(num,"x 6 =",num*6)
    print(num,"x 7 =",num*7)
    print(num,"x 8 =",num*8)
    print(num,"x 9 =",num*9)
    print(num,"x 10 =",num*10)
    print(num,"x 11 =",num*11)
    print(num,"x 12 =",num*12)
elif table.lower()=="division":
    print(num,"/ 1 =",num/1)
    print(num,"/ 2 =",num/2)
    print(num,"/ 3 =",num/3)
    print(num,"/ 4 =",num/4)
    print(num,"/ 5 =",num/5)
    print(num,"/ 6 =",num/6)
    print(num,"/ 7 =",num/7)
    print(num,"/ 8 =",num/8)
    print(num,"/ 9 =",num/9)
    print(num,"/ 10 =",num/10)
    print(num,"/ 11 =",num/11)
    print(num,"/ 12 =",num/12)
elif table.lower()=="addition":
    print(num,"+ 1 =",num+1)
    print(num,"+ 2 =",num+2)
    print(num,"+ 3 =",num+3)
    print(num,"+ 4 =",num+4)
    print(num,"+ 5 =",num+5)
    print(num,"+ 6 =",num+6)
    print(num,"+ 7 =",num+7)
    print(num,"+ 8 =",num+8)
    print(num,"+ 9 =",num+9)
    print(num,"+ 10 =",num+10)
    print(num,"+ 11 =",num+11)
    print(num,"+ 12 =",num+12)
elif table.lower()=="substraction":
    print(num,"- 1 =",num-1)
    print(num,"- 2 =",num-2)
    print(num,"- 3 =",num-3)
    print(num,"- 4 =",num-4)
    print(num,"- 5 =",num-5)
    print(num,"- 6 =",num-6)
    print(num,"- 7 =",num-7)
    print(num,"- 8 =",num-8)
    print(num,"- 9 =",num-9)
    print(num,"- 10 =",num-10)
    print(num,"- 11 =",num-11)
    print(num,"- 12 =",num-12)
        
    
